const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {load,save,id,usePostgres}=require('./db');let db;
const PORT=process.env.PORT||5000;const root=path.join(__dirname,'..');
const SESSION_TTL_MS=30*24*60*60*1000;
const authAttempts=new Map();
function rateLimit(req,key,limit=8,windowMs=15*60*1000){const nowMs=Date.now(),ip=req.socket?.remoteAddress||'local',k=ip+':'+key;let a=authAttempts.get(k)||[];a=a.filter(t=>nowMs-t<windowMs);if(a.length>=limit)return false;a.push(nowMs);authAttempts.set(k,a);return true}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function strongPassword(v){return typeof v==='string'&&v.length>=8&&v.length<=128&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/\d/.test(v)}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});res.end(body)}function hash(p,salt=crypto.randomBytes(16).toString('hex')){return salt+':'+crypto.scryptSync(p,salt,64).toString('hex')}function check(p,h){const [salt,digest]=String(h).split(':');if(!salt||!digest)return false;return crypto.timingSafeEqual(Buffer.from(digest,'hex'),crypto.scryptSync(p,salt,64))}function token(){return crypto.randomBytes(32).toString('hex')}function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const tokenValue=h.slice(7);const s=db.sessions.find(x=>x.token===tokenValue);if(!s)return null;const created=Date.parse(s.created_at||'');if(!created||Date.now()-created>SESSION_TTL_MS){db.sessions=db.sessions.filter(x=>x.token!==tokenValue);return null}return db.users.find(u=>u.id===s.userId)||null}function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}function pub(u){return u&&{id:u.id,name:u.name,email:u.email,role:u.role,phone:u.phone,created_at:u.created_at}}function now(){return new Date().toISOString()}
async function ensureAdmin(){
  db.users=db.users.filter(u=>!/^test-|^qa-|^authtest@/i.test(String(u.email||'')));
  let u=db.users.find(x=>x.role==='admin');
  if(!u){u={id:id(db,'user'),name:'Phoenix Garage Admin',email:'admin@phoenixgarage.local',password_hash:hash('Admin@12345'),role:'admin',phone:'',created_at:now()};db.users.push(u);await save(db)}
}

function adminAuth(req){const u=auth(req);return u&&u.role==='admin'?u:null}
function adminOnly(req,res){const u=adminAuth(req);if(!u){json(res,403,{error:'Administrator access required'});return null}return u}
function b2bCompanyFor(u){if(!u)return null;return (db.b2bCompanies||[]).find(c=>c.owner_user_id===u.id||(db.b2bMembers||[]).some(m=>m.company_id===c.id&&m.user_id===u.id))||null}
function b2bUser(req){const u=auth(req);if(!u)return null;return ['manufacturer','distributor','b2b_staff'].includes(u.role)?u:null}
function b2bAllowed(req,res){const u=b2bUser(req);if(!u){json(res,403,{error:'Approved B2B account required'});return null}return u}

function owner(req){const u=auth(req);if(u)return {type:'user',id:String(u.id)};const v=String(req.headers['x-visitor-id']||'').trim();return v&&/^[A-Za-z0-9_-]{8,80}$/.test(v)?{type:'visitor',id:v}:null}
function ownerItems(req,kind){const o=owner(req);if(!o)return {o:null,items:[]};return {o,items:kind==='wishlist'?db.wishlistItems.filter(x=>x.owner_type===o.type&&x.owner_id===o.id):db.cartItems.filter(x=>x.owner_type===o.type&&x.owner_id===o.id)}}
function productOut(p){return {id:p.id,name:p.name,cat:p.category,category:p.category,category_id:p.category_id||'',subcategory:p.subcategory||'',product_kind:p.product_kind||'part',fitment_level:p.fitment_level||'vehicle_specific',price:p.price,old:p.old_price,old_price:p.old_price,icon:p.icon,fit:p.fit,type:p.type,brand:p.brand,oem:p.oem,sku:p.sku||p.oem,part_number:p.part_number||p.oem,oem_reference:p.oem_reference||p.oem,image:p.image||'',stock:p.stock,tag:p.tag,description:p.description||'',features:p.features||[],specifications:p.specifications||{},unit:p.unit||'piece',pack_quantity:Number(p.pack_quantity||1),warranty:p.warranty||'',rating:Number(p.rating||0),reviews:Number(p.reviews||0),delivery:p.delivery||'',condition:p.condition||'New',manufacturer_type:p.manufacturer_type||'Manufacturer',seller_name:p.seller_name||'',verified_fitment:Boolean(p.verified_fitment),gst_rate:Number(p.gst_rate||18),return_days:Number(p.return_days||0),fitment:p.fitment||[]}}
function sendFile(req,res){let url=new URL(req.url,'http://localhost');let pathname=decodeURIComponent(url.pathname);if(pathname==='/')pathname='/index.html';let file=path.join(root,pathname);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}let ext=path.extname(file);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store, no-cache, must-revalidate'});fs.createReadStream(file).pipe(res)}
async function api(req,res,url){if(req.method==='OPTIONS')return json(res,204,{});const p=url.pathname;try{
if(p==='/api/health')return json(res,200,{ok:true,service:'PHOENIX GARAGE',phase:'16',database:usePostgres?'postgresql':'sqlite',online:usePostgres});
if(p==='/api/b2b/apply'&&req.method==='POST'){
 if(!rateLimit(req,'b2b-apply',5))return json(res,429,{error:'Too many applications. Try again later.'});
 const b=await body(req),name=String(b.name||'').trim(),email=String(b.email||'').toLowerCase().trim(),password=b.password,company=String(b.company_name||'').trim(),businessType=String(b.business_type||'').toLowerCase(),gstin=String(b.gstin||'').trim(),address=String(b.address||'').trim(),phone=String(b.phone||'').trim();
 if(!company||company.length<2||company.length>120)return json(res,400,{error:'Company name must be 2–120 characters'});
 if(!['manufacturer','distributor'].includes(businessType))return json(res,400,{error:'Select Manufacturer or Distributor'});
 if(gstin.length<3||gstin.length>30)return json(res,400,{error:'Enter a valid GSTIN/business tax ID'});
 if(address.length<5)return json(res,400,{error:'Registered business address is required'});
 if(!name||name.length<2||name.length>80)return json(res,400,{error:'Primary contact name must be 2–80 characters'});
 if(!phone||!/^[0-9+()\-\s]{7,20}$/.test(phone))return json(res,400,{error:'Business phone must contain 7–20 valid phone characters'});
 if(!validEmail(email))return json(res,400,{error:'Enter a valid business email address'});
 if(!strongPassword(password))return json(res,400,{error:'Password must be 8–128 characters and include uppercase, lowercase, and a number'});
 const website=String(b.website||'').trim();
 if(website&&!/^https?:\/\//i.test(website))return json(res,400,{error:'Website must start with http:// or https://'});
 if(db.users.some(u=>u.email===email)||db.b2bApplications.some(a=>a.email===email&&a.status==='pending'))return json(res,409,{error:'An account or pending application already exists for this email'});
 const a={id:id(db,'b2bApplication'),name,email,password_hash:hash(password),phone,company_name:company,business_type:businessType,gstin,address,website,status:'pending',created_at:now()};db.b2bApplications.push(a);await save(db);return json(res,201,{application_id:a.id,status:a.status,message:'Application submitted for Phoenix Garage administration review'})}
if(p==='/api/auth/register'&&req.method==='POST'){if(!rateLimit(req,'register',5))return json(res,429,{error:'Too many registration attempts. Try again later.'});const b=await body(req),name=String(b.name||'').trim(),email=String(b.email||'').toLowerCase().trim(),password=b.password;if(!name||name.length<2||name.length>80||!validEmail(email)||!strongPassword(password))return json(res,400,{error:'Use a valid name, email, and password with 8+ characters including uppercase, lowercase, and a number'});const role=b.role||'customer';if(!['customer','workshop'].includes(role))return json(res,403,{error:'Business accounts are created through Phoenix Garage administration'});if(db.users.some(u=>u.email===email))return json(res,409,{error:'An account with that email already exists'});const u={id:id(db,'user'),name,email,password_hash:hash(password),role,phone:String(b.phone||'').trim(),created_at:now()};db.users.push(u);const t=token();db.sessions.push({id:id(db,'session'),token:t,userId:u.id,created_at:now()});await save(db);return json(res,201,{token:t,user:pub(u)})}
if(p==='/api/auth/login'&&req.method==='POST'){if(!rateLimit(req,'login',10))return json(res,429,{error:'Too many sign-in attempts. Try again later.'});const b=await body(req),email=String(b.email||'').toLowerCase().trim(),u=db.users.find(x=>x.email===email);let ok=false;try{ok=!!u&&check(String(b.password||''),u.password_hash)}catch{}if(!ok)return json(res,401,{error:'Invalid email or password'});const t=token();db.sessions.push({id:id(db,'session'),token:t,userId:u.id,created_at:now()});await save(db);return json(res,200,{token:t,user:pub(u)})}
if(p==='/api/auth/me'&&req.method==='GET'){const u=auth(req);return u?json(res,200,{user:pub(u)}):json(res,401,{error:'Authentication required'})}
if(p==='/api/auth/logout'&&req.method==='POST'){const h=req.headers.authorization||'';if(h.startsWith('Bearer ')){const tv=h.slice(7);db.sessions=db.sessions.filter(x=>x.token!==tv);await save(db)}return json(res,200,{ok:true})}
if(p==='/api/catalog/categories'&&req.method==='GET'){const counts={};for(const x of db.products)counts[x.category_id]=(counts[x.category_id]||0)+1;return json(res,200,(db.categories||[]).map(c=>({...c,product_count:counts[c.id]||0})))}
if(p==='/api/catalog/stats'&&req.method==='GET'){const vehicles=db.vehicles;return json(res,200,{categories:(db.categories||[]).length,products:products.length,vehicles:vehicles.length,vehicle_specific:products.filter(x=>x.fitment_level==='vehicle_specific').length,verified_fitment:products.filter(x=>x.verified_fitment).length})}
if(p==='/api/products'&&req.method==='GET'){const q=url.searchParams.get('q')?.toLowerCase()||'',cat=url.searchParams.get('category')||'',type=url.searchParams.get('type')||'',brand=url.searchParams.get('brand')||'',condition=url.searchParams.get('condition')||'',availability=url.searchParams.get('availability')||'',min=url.searchParams.get('min'),max=url.searchParams.get('max'),subcategory=url.searchParams.get('subcategory')||'',categoryId=url.searchParams.get('category_id')||'',vehicleId=Number(url.searchParams.get('vehicle_id')||0),sort=url.searchParams.get('sort')||'featured';const v=vehicleId?db.vehicles.find(x=>x.id===vehicleId):null;let a=db.products.filter(x=>(!q||(x.name+' '+x.category+' '+x.brand+' '+x.oem+' '+(x.sku||'')+' '+x.fit).toLowerCase().includes(q))&&(!cat||x.category===cat)&&(!categoryId||x.category_id===categoryId)&&(!subcategory||x.subcategory===subcategory)&&(!type||x.type.includes(type)||x.type==='Car & Bike')&&(!brand||x.brand===brand)&&(!condition||x.condition===condition)&&(!availability||(availability==='in-stock'?x.stock>0:x.stock===0))&&(!min||x.price>=Number(min))&&(!max||x.price<=Number(max))&&(!v||((x.type.includes(v.type)||x.type==='Car & Bike')&&(x.fitment||[]).includes(v.id))));if(sort==='price-asc')a.sort((x,y)=>x.price-y.price);else if(sort==='price-desc')a.sort((x,y)=>y.price-x.price);else if(sort==='rating')a.sort((x,y)=>(y.rating||0)-(x.rating||0));else if(sort==='newest')a.sort((x,y)=>y.id-x.id);return json(res,200,a.map(productOut))}
if(p==='/api/search/suggestions'&&req.method==='GET'){const q=url.searchParams.get('q')?.trim().toLowerCase()||'';if(q.length<2)return json(res,200,[]);const out=[];for(const x of db.products){const hay=[x.name,x.brand,x.oem,x.sku,x.part_number,x.category].filter(Boolean).join(' ').toLowerCase();if(hay.includes(q))out.push({id:x.id,name:x.name,brand:x.brand,part_number:x.part_number||x.oem,category:x.category});if(out.length>=8)break}return json(res,200,out)}
if(p.startsWith('/api/products/')&&req.method==='GET'){const pdt=db.products.find(x=>x.id===Number(p.split('/').pop()));if(!pdt)return json(res,404,{error:'Product not found'});return json(res,200,{...productOut(pdt),fitment:pdt.fitment||[]})}
if(p==='/api/vehicles'&&req.method==='GET')return json(res,200,db.vehicles);
if(p.match(/^\/api\/vehicles\/\d+\/products$/)&&req.method==='GET'){const v=db.vehicles.find(x=>x.id===Number(p.split('/')[3]));if(!v)return json(res,404,{error:'Vehicle not found'});return json(res,200,db.products.filter(x=>(x.type.includes(v.type)||x.type==='Car & Bike')&&(x.fitment||[]).includes(v.id)&&x.stock>0).map(productOut))}
if(p==='/api/wishlist'&&req.method==='GET'){const {items}=ownerItems(req,'wishlist');return json(res,200,items.map(x=>productOut(db.products.find(p=>p.id===x.product_id))).filter(Boolean))}
if(p==='/api/wishlist'&&req.method==='POST'){const {o}=ownerItems(req,'wishlist');if(!o)return json(res,400,{error:'Visitor ID required'});const b=await body(req),pid=Number(b.product_id);if(!db.products.some(x=>x.id===pid))return json(res,404,{error:'Product not found'});if(!db.wishlistItems.some(x=>x.owner_type===o.type&&x.owner_id===o.id&&x.product_id===pid))db.wishlistItems.push({id:db.wishlistItems.length?Math.max(...db.wishlistItems.map(x=>x.id))+1:1,owner_type:o.type,owner_id:o.id,product_id:pid,created_at:now()});await save(db);return json(res,201,{ok:true})}
if(p.match(/^\/api\/wishlist\/\d+$/)&&req.method==='DELETE'){const {o}=ownerItems(req,'wishlist');if(!o)return json(res,400,{error:'Visitor ID required'});const pid=Number(p.split('/').pop());db.wishlistItems=db.wishlistItems.filter(x=>!(x.owner_type===o.type&&x.owner_id===o.id&&x.product_id===pid));await save(db);return json(res,204,{})}
if(p==='/api/cart'&&req.method==='GET'){const {items}=ownerItems(req,'cart');return json(res,200,items.map(x=>({id:x.product_id,qty:x.qty,product:productOut(db.products.find(p=>p.id===x.product_id))})).filter(x=>x.product))}
if(p==='/api/cart'&&req.method==='POST'){const {o}=ownerItems(req,'cart');if(!o)return json(res,400,{error:'Visitor ID required'});const b=await body(req),pid=Number(b.product_id),qty=Math.max(1,Number(b.qty)||1);if(!db.products.some(x=>x.id===pid))return json(res,404,{error:'Product not found'});const row=db.cartItems.find(x=>x.owner_type===o.type&&x.owner_id===o.id&&x.product_id===pid);if(row)row.qty+=qty;else db.cartItems.push({id:db.cartItems.length?Math.max(...db.cartItems.map(x=>x.id))+1:1,owner_type:o.type,owner_id:o.id,product_id:pid,qty,created_at:now()});await save(db);return json(res,201,{ok:true})}
if(p.match(/^\/api\/cart\/\d+$/)&&req.method==='DELETE'){const {o}=ownerItems(req,'cart');if(!o)return json(res,400,{error:'Visitor ID required'});const pid=Number(p.split('/').pop());db.cartItems=db.cartItems.filter(x=>!(x.owner_type===o.type&&x.owner_id===o.id&&x.product_id===pid));await save(db);return json(res,204,{})}
if(p.match(/^\/api\/cart\/\d+$/)&&req.method==='PATCH'){const {o}=ownerItems(req,'cart');if(!o)return json(res,400,{error:'Visitor ID required'});const pid=Number(p.split('/').pop()),b=await body(req),qty=Math.max(0,Number(b.qty)||0);const row=db.cartItems.find(x=>x.owner_type===o.type&&x.owner_id===o.id&&x.product_id===pid);if(!row)return json(res,404,{error:'Cart item not found'});if(qty===0)db.cartItems=db.cartItems.filter(x=>x!==row);else row.qty=qty;await save(db);return json(res,200,{ok:true})}
if(p==='/api/account'&&req.method==='GET'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const addresses=db.addresses.filter(a=>a.user_id===u.id).sort((a,b)=>Number(b.is_default)-Number(a.is_default)||b.id-a.id);const vehicles=db.userVehicles.filter(uv=>uv.user_id===u.id).map(uv=>({...uv,...db.vehicles.find(v=>v.id===uv.vehicle_id)}));const orders=db.orders.filter(o=>o.user_id===u.id).sort((a,b)=>b.id-a.id);const wishlist=db.wishlistItems.filter(x=>x.owner_type==='user'&&x.owner_id===String(u.id)).map(x=>productOut(db.products.find(p=>p.id===x.product_id))).filter(Boolean);return json(res,200,{user:pub(u),addresses,vehicles,orders,wishlist})}
if(p==='/api/account/profile'&&req.method==='PATCH'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const b=await body(req),name=String(b.name??u.name).trim(),phone=String(b.phone??(u.phone||'')).trim();if(name.length<2||name.length>80)return json(res,400,{error:'Name must be between 2 and 80 characters'});if(phone.length>40)return json(res,400,{error:'Phone number is too long'});u.name=name;u.phone=phone;await save(db);return json(res,200,{user:pub(u)})}
if(p==='/api/account/password'&&req.method==='POST'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const b=await body(req);let ok=false;try{ok=check(String(b.current_password||''),u.password_hash)}catch{}if(!ok)return json(res,400,{error:'Current password is incorrect'});if(!strongPassword(b.new_password))return json(res,400,{error:'New password must be 8+ characters with uppercase, lowercase and a number'});u.password_hash=hash(b.new_password);db.sessions=db.sessions.filter(s=>s.userId!==u.id);const t=token();db.sessions.push({id:id(db,'session'),token:t,userId:u.id,created_at:now()});await save(db);return json(res,200,{token:t,user:pub(u)})}
if(p==='/api/account/addresses'&&req.method==='POST'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const b=await body(req);if(!b.full_name||!b.phone||!b.address||!b.city||!b.state||!b.pincode)return json(res,400,{error:'Complete address is required'});if(b.is_default||!db.addresses.some(a=>a.user_id===u.id))db.addresses.filter(a=>a.user_id===u.id).forEach(a=>a.is_default=0);const a={id:id(db,'address'),user_id:u.id,label:String(b.label||'Home').slice(0,30),full_name:String(b.full_name).trim(),phone:String(b.phone).trim(),address:String(b.address).trim(),city:String(b.city).trim(),state:String(b.state).trim(),pincode:String(b.pincode).trim(),is_default:(b.is_default||!db.addresses.some(x=>x.user_id===u.id))?1:0};db.addresses.push(a);await save(db);return json(res,201,a)}
if(p.match(/^\/api\/account\/addresses\/\d+$/)&&req.method==='PATCH'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const aid=Number(p.split('/').pop()),a=db.addresses.find(x=>x.id===aid&&x.user_id===u.id);if(!a)return json(res,404,{error:'Address not found'});const b=await body(req);for(const k of ['label','full_name','phone','address','city','state','pincode'])if(b[k]!==undefined)a[k]=String(b[k]).trim();if(!a.full_name||!a.phone||!a.address||!a.city||!a.state||!a.pincode)return json(res,400,{error:'Complete address is required'});if(b.is_default)db.addresses.filter(x=>x.user_id===u.id).forEach(x=>x.is_default=x.id===a.id?1:0);await save(db);return json(res,200,a)}
if(p.match(/^\/api\/account\/addresses\/\d+\/default$/)&&req.method==='POST'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const aid=Number(p.split('/')[4]),a=db.addresses.find(x=>x.id===aid&&x.user_id===u.id);if(!a)return json(res,404,{error:'Address not found'});db.addresses.filter(x=>x.user_id===u.id).forEach(x=>x.is_default=x.id===a.id?1:0);await save(db);return json(res,200,a)}
if(p.match(/^\/api\/account\/addresses\/\d+$/)&&req.method==='DELETE'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const aid=Number(p.split('/').pop()),a=db.addresses.find(x=>x.id===aid&&x.user_id===u.id);if(!a)return json(res,404,{error:'Address not found'});db.addresses=db.addresses.filter(x=>x.id!==aid||x.user_id!==u.id);if(a.is_default){const next=db.addresses.filter(x=>x.user_id===u.id).sort((x,y)=>y.id-x.id)[0];if(next)next.is_default=1}await save(db);return json(res,204,{})}
if(p==='/api/account/vehicles'&&req.method==='POST'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const b=await body(req),v=db.vehicles.find(x=>x.id===Number(b.vehicle_id));if(!v)return json(res,404,{error:'Vehicle not found'});if(b.is_primary)db.userVehicles.filter(x=>x.user_id===u.id).forEach(x=>x.is_primary=0);let uv=db.userVehicles.find(x=>x.user_id===u.id&&x.vehicle_id===v.id);if(!uv){uv={id:id(db,'userVehicle'),user_id:u.id,vehicle_id:v.id,is_primary:b.is_primary?1:0};db.userVehicles.push(uv)}else uv.is_primary=b.is_primary?1:0;await save(db);return json(res,201,v)}
if(p.match(/^\/api\/account\/vehicles\/\d+$/)&&req.method==='DELETE'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const uid=Number(p.split('/').pop());db.userVehicles=db.userVehicles.filter(x=>!(x.id===uid&&x.user_id===u.id));await save(db);return json(res,204,{})}
if(p==='/api/orders'&&req.method==='GET'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});return json(res,200,db.orders.filter(o=>o.user_id===u.id).sort((a,b)=>b.id-a.id))}
if(p==='/api/contact'&&req.method==='POST'){const b=await body(req);if(!b.name||!b.email||!b.message)return json(res,400,{error:'Name, email and message are required'});const m={id:id(db,'message'),name:String(b.name),email:String(b.email),phone:String(b.phone||''),topic:String(b.topic||'General enquiry'),message:String(b.message),status:'new',created_at:now()};db.messages.push(m);await save(db);return json(res,201,{ok:true,message_id:m.id})}
if(p==='/api/bookings'&&req.method==='POST'){const b=await body(req);if(!b.name||!b.phone||!b.email||!b.service||!b.vehicle||!b.date)return json(res,400,{error:'Name, phone, email, service, vehicle and date are required'});const m={id:id(db,'booking'),name:String(b.name),phone:String(b.phone),email:String(b.email),service:String(b.service),vehicle:String(b.vehicle),date:String(b.date),notes:String(b.notes||''),status:'requested',created_at:now()};db.bookings.push(m);await save(db);return json(res,201,{ok:true,booking_id:m.id,status:m.status})}
if(p==='/api/admin/b2b/applications'&&req.method==='GET'){if(!adminOnly(req,res))return;return json(res,200,db.b2bApplications.slice().sort((a,b)=>b.id-a.id).map(a=>{const x={...a};delete x.password_hash;return x}))}
if(p.match(/^\/api\/admin\/b2b\/applications\/\d+$/)&&req.method==='PATCH'){const admin=adminOnly(req,res);if(!admin)return;const aid=Number(p.split('/').pop()),a=db.b2bApplications.find(x=>x.id===aid);if(!a)return json(res,404,{error:'Application not found'});const b=await body(req),status=String(b.status||'').toLowerCase();if(!['approved','rejected'].includes(status))return json(res,400,{error:'Invalid application status'});if(a.status!=='pending')return json(res,409,{error:'Application has already been reviewed'});if(status==='rejected'){a.status='rejected';a.reviewed_at=now();a.reviewed_by=admin.id;await save(db);return json(res,200,{status:a.status})}
 if(db.users.some(u=>u.email===a.email))return json(res,409,{error:'A user with this email already exists'});
 const company={id:id(db,'b2bCompany'),name:a.company_name,business_type:a.business_type,gstin:a.gstin,address:a.address,phone:a.phone,website:a.website,owner_user_id:0,created_at:now(),status:'active'};
 const u={id:id(db,'user'),name:a.name,email:a.email,password_hash:a.password_hash,role:a.business_type,phone:a.phone,company_id:company.id,created_at:now()};company.owner_user_id=u.id;db.b2bCompanies.push(company);db.users.push(u);db.b2bMembers.push({id:id(db,'b2bMember'),company_id:company.id,user_id:u.id,role:'owner',created_at:now()});a.status='approved';a.reviewed_at=now();a.reviewed_by=admin.id;a.company_id=company.id;await save(db);return json(res,200,{status:a.status,company_id:company.id,user:pub(u)})}
if(p==='/api/admin/overview'&&req.method==='GET'){const u=adminOnly(req,res);if(!u)return;const low=db.products.filter(x=>Number(x.stock||0)<=5&&Number(x.stock||0)>0).length;const recent=db.orders.slice().sort((a,b)=>b.id-a.id).slice(0,8).map(o=>({...o,customer_name:db.users.find(x=>x.id===o.user_id)?.name||'Customer'}));const apps=db.b2bApplications||[];return json(res,200,{stats:{products:db.products.length,orders:db.orders.length,users:db.users.length,low_stock:low,b2b_pending:apps.filter(x=>x.status==='pending').length,b2b_approved:apps.filter(x=>x.status==='approved').length,b2b_rejected:apps.filter(x=>x.status==='rejected').length,b2b_companies:(db.b2bCompanies||[]).filter(x=>x.status==='active').length},inventory:{in_stock:db.products.filter(x=>Number(x.stock||0)>0).length,out_of_stock:db.products.filter(x=>Number(x.stock||0)<=0).length,low_stock:low},recent_orders:recent})}
if(p==='/api/admin/products'&&req.method==='GET'){if(!adminOnly(req,res))return;return json(res,200,db.products.slice().sort((a,b)=>b.id-a.id).map(productOut))}
if(p==='/api/admin/products'&&req.method==='POST'){if(!adminOnly(req,res))return;const b=await body(req);const name=String(b.name||'').trim();const price=Number(b.price);if(!name||!Number.isFinite(price)||price<0)return json(res,400,{error:'Product name and valid price are required'});const pid=id(db,'product');const pdt={id:pid,name,category:String(b.category||'Accessories'),cat:String(b.category||'Accessories'),category_id:String(b.category_id||'accessories'),subcategory:String(b.subcategory||'General'),product_kind:'part',fitment_level:'vehicle_specific',price,old_price:Number(b.old_price||price),old:Number(b.old_price||price),icon:'',image:String(b.image||'assets/products/1.svg'),fit:String(b.fit||'Vehicle fitment verification required'),type:String(b.type||'Car & Bike'),brand:String(b.brand||'Phoenix Garage'),oem:String(b.oem||'Not supplied'),sku:String(b.sku||('PG-'+pid)),part_number:String(b.part_number||b.sku||('PG-'+pid)),oem_reference:String(b.oem_reference||'Not supplied'),stock:Math.max(0,Number(b.stock||0)),tag:'New',rating:0,reviews:0,delivery:'2–7 days',warranty:String(b.warranty||'1 year'),condition:'New',manufacturer_type:'Manufacturer',seller_id:null,seller_name:'Phoenix Garage',gst_rate:18,return_days:7,description:String(b.description||''),features:[],specifications:{},verified_fitment:false,fitment:[]};db.products.push(pdt);await save(db);return json(res,201,productOut(pdt))}
if(p.match(/^\/api\/admin\/products\/\d+$/)&&req.method==='PATCH'){if(!adminOnly(req,res))return;const pid=Number(p.split('/').pop()),pdt=db.products.find(x=>x.id===pid);if(!pdt)return json(res,404,{error:'Product not found'});const b=await body(req);for(const k of ['name','category','category_id','subcategory','price','old_price','stock','description','image','brand','oem','sku','part_number','warranty','fit','type'])if(b[k]!==undefined)pdt[k]=k==='price'||k==='old_price'||k==='stock'?Number(b[k]):String(b[k]);pdt.cat=pdt.category;pdt.old=pdt.old_price;await save(db);return json(res,200,productOut(pdt))}
if(p.match(/^\/api\/admin\/products\/\d+$/)&&req.method==='DELETE'){if(!adminOnly(req,res))return;const pid=Number(p.split('/').pop()),before=db.products.length;db.products.splice(0,db.products.length,...db.products.filter(x=>x.id!==pid));if(db.products.length===before)return json(res,404,{error:'Product not found'});db.wishlistItems=db.wishlistItems.filter(x=>x.product_id!==pid);db.cartItems=db.cartItems.filter(x=>x.product_id!==pid);await save(db);return json(res,204,{})}
if(p==='/api/admin/orders'&&req.method==='GET'){if(!adminOnly(req,res))return;const status=url.searchParams.get('status')||'';return json(res,200,db.orders.slice().filter(o=>!status||o.status===status).sort((a,b)=>b.id-a.id).map(o=>({...o,customer_name:db.users.find(x=>x.id===o.user_id)?.name||'Customer',customer_email:db.users.find(x=>x.id===o.user_id)?.email||''})))}
if(p.match(/^\/api\/admin\/orders\/\d+$/)&&req.method==='PATCH'){if(!adminOnly(req,res))return;const oid=Number(p.split('/').pop()),o=db.orders.find(x=>x.id===oid);if(!o)return json(res,404,{error:'Order not found'});const b=await body(req),allowed=['placed','processing','shipped','delivered','cancelled'];if(!allowed.includes(b.status))return json(res,400,{error:'Invalid order status'});if(o.status==='cancelled'&&b.status!=='cancelled')return json(res,400,{error:'Cancelled orders cannot be reopened'});if(o.status!=='cancelled'&&b.status==='cancelled'){for(const i of o.items||[]){const pr=db.products.find(x=>x.id===i.product_id);if(pr)pr.stock=Number(pr.stock||0)+Number(i.qty||0)}}o.status=b.status;o.updated_at=now();o.status_history=Array.isArray(o.status_history)?o.status_history:[];o.status_history.push({status:b.status,at:o.updated_at,by:'admin'});await save(db);return json(res,200,o)}
if(p==='/api/admin/users'&&req.method==='GET'){if(!adminOnly(req,res))return;return json(res,200,db.users.slice().sort((a,b)=>b.id-a.id).map(pub))}
if(p==='/api/admin/categories'&&req.method==='GET'){if(!adminOnly(req,res))return;const counts={};db.products.forEach(x=>counts[x.category_id]=(counts[x.category_id]||0)+1);return json(res,200,(db.categories||[]).map(c=>({...c,product_count:counts[c.id]||0})))}
if(p==='/api/admin/categories'&&req.method==='POST'){if(!adminOnly(req,res))return;const b=await body(req),cid=String(b.id||'').trim().toLowerCase().replace(/\s+/g,'-'),name=String(b.name||'').trim();if(!cid||!name)return json(res,400,{error:'Category ID and name are required'});if(db.categories.some(x=>x.id===cid))return json(res,409,{error:'Category already exists'});db.categories.push({id:cid,name});await save(db);return json(res,201,{id:cid,name})}
if(p.match(/^\/api\/admin\/categories\/.+$/)&&req.method==='PATCH'){if(!adminOnly(req,res))return;const cid=decodeURIComponent(p.split('/').pop()),c=db.categories.find(x=>x.id===cid);if(!c)return json(res,404,{error:'Category not found'});const b=await body(req);if(!String(b.name||'').trim())return json(res,400,{error:'Category name is required'});c.name=String(b.name).trim();await save(db);return json(res,200,c)}
if(p==='/api/admin/messages'&&req.method==='GET'){if(!adminOnly(req,res))return;return json(res,200,db.messages.slice().sort((a,b)=>b.id-a.id))}
if(p==='/api/admin/bookings'&&req.method==='GET'){if(!adminOnly(req,res))return;return json(res,200,db.bookings.slice().sort((a,b)=>b.id-a.id))}
if(p==='/api/b2b/stats'&&req.method==='GET'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u),mine=db.products.filter(x=>x.company_id===c?.id||x.seller_id===u.id||x.seller_name===u.name);return json(res,200,{role:u.role,company:c,products:mine.length,units:mine.reduce((n,x)=>n+Number(x.stock||0),0),orders:db.orders.filter(x=>x.items?.some(i=>mine.some(p=>p.id===i.product_id))).length,customers:new Set(db.orders.map(x=>x.user_id)).size})}
if(p==='/api/b2b/products'&&req.method==='GET'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u);return json(res,200,db.products.filter(x=>x.company_id===c?.id||x.seller_id===u.id||x.seller_name===u.name).map(productOut))}
if(p==='/api/b2b/products'&&req.method==='POST'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u);if(!c)return json(res,403,{error:'B2B company not found'});const b=await body(req);if(!b.name||!b.price)return json(res,400,{error:'Name and price are required'});const pid=id(db,'product');const pdt={id:pid,name:String(b.name),category:String(b.category||'Accessories'),cat:String(b.category||'Accessories'),category_id:String(b.category_id||'accessories'),subcategory:String(b.subcategory||'General'),product_kind:'b2b_listing',fitment_level:'vehicle_specific',price:Number(b.price),old_price:Number(b.old_price||b.price),old:Number(b.old_price||b.price),icon:'',image:String(b.image||'assets/products/brake-pads.jpg'),fit:String(b.fit||'Vehicle fitment verification required'),type:String(b.type||'Car & Bike'),brand:String(b.brand||u.name),oem:String(b.oem||'Not supplied'),sku:String(b.sku||('B2B-'+pid)),part_number:String(b.part_number||b.sku||('B2B-'+pid)),oem_reference:String(b.oem_reference||'Not supplied'),stock:Math.max(0,Number(b.stock||0)),tag:'B2B',rating:0,reviews:0,delivery:'2–7 days',warranty:String(b.warranty||'Seller warranty'),condition:'New',manufacturer_type:u.role,seller_id:u.id,seller_name:c.name,company_id:c.id,gst_rate:18,return_days:7,description:String(b.description||''),features:Array.isArray(b.features)?b.features:[],specifications:b.specifications||{},verified_fitment:false,fitment:Array.isArray(b.fitment)?b.fitment:[]};db.products.push(pdt);await save(db);return json(res,201,productOut(pdt))}
if(p.match(/^\/api\/b2b\/products\/\d+$/)&&req.method==='PATCH'){const u=auth(req);if(!u||!['manufacturer','distributor'].includes(u.role))return json(res,403,{error:'Manufacturer or distributor account required'});const pid=Number(p.split('/').pop()),pdt=db.products.find(x=>x.id===pid&&(x.seller_id===u.id||x.seller_name===u.name));if(!pdt)return json(res,404,{error:'Product not found'});const b=await body(req);for(const k of ['name','category','category_id','subcategory','price','old_price','stock','description','image','brand','oem','sku','part_number','warranty','fit','type'])if(b[k]!==undefined)pdt[k]=b[k];pdt.cat=pdt.category;pdt.old=pdt.old_price;await save(db);return json(res,200,productOut(pdt))}
if(p.match(/^\/api\/b2b\/products\/\d+$/)&&req.method==='DELETE'){const u=auth(req);if(!u||!['manufacturer','distributor'].includes(u.role))return json(res,403,{error:'Manufacturer or distributor account required'});const pid=Number(p.split('/').pop());const before=db.products.length;db.products=db.products.filter(x=>!(x.id===pid&&(x.seller_id===u.id||x.seller_name===u.name)));if(db.products.length===before)return json(res,404,{error:'Product not found'});await save(db);return json(res,204,{})}
if(p.match(/^\/api\/orders\/\d+$/)&&req.method==='GET'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const oid=Number(p.split('/').pop()),o=db.orders.find(x=>x.id===oid&&x.user_id===u.id);return o?json(res,200,o):json(res,404,{error:'Order not found'})}
if(p==='/api/orders'&&req.method==='POST'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const b=await body(req);if(!Array.isArray(b.items)||!b.items.length||!b.shipping)return json(res,400,{error:'Items and shipping address are required'});let subtotal=0,items=[];for(const i of b.items){const pr=db.products.find(x=>x.id===Number(i.id)),qty=Math.max(1,Number(i.qty)||1);if(!pr)return json(res,400,{error:'Product not found'});if(pr.stock<qty)return json(res,409,{error:`Only ${pr.stock} units available for ${pr.name}`});subtotal+=pr.price*qty;items.push({product_id:pr.id,name:pr.name,oem:pr.oem,qty,unit_price:pr.price});}for(const i of items)db.products.find(x=>x.id===i.product_id).stock-=i.qty;const shipping=[b.shipping.full_name,b.shipping.phone,b.shipping.address,b.shipping.city,b.shipping.state,b.shipping.pincode].filter(Boolean).join(', ');const o={id:id(db,'order'),user_id:u.id,status:'placed',subtotal,total:subtotal,shipping_address:shipping,created_at:now(),items};db.orders.push(o);await save(db);return json(res,201,{order_id:o.id,status:o.status,subtotal:o.subtotal,total:o.total})}
if(p.match(/^\/api\/orders\/\d+$/)&&req.method==='GET'){const u=auth(req);if(!u)return json(res,401,{error:'Authentication required'});const o=db.orders.find(x=>x.id===Number(p.split('/').pop())&&x.user_id===u.id);return o?json(res,200,o):json(res,404,{error:'Order not found'})}
if(p==='/api/b2b/company'&&req.method==='GET'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u);if(!c)return json(res,404,{error:'B2B company not found'});const members=db.b2bMembers.filter(m=>m.company_id===c.id).map(m=>({...m,user:pub(db.users.find(x=>x.id===m.user_id))}));return json(res,200,{company:c,members})}
if(p==='/api/b2b/company'&&req.method==='PATCH'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u);if(!c||c.owner_user_id!==u.id)return json(res,403,{error:'Only the company owner can edit company details'});const b=await body(req);for(const k of ['name','gstin','website','address','phone'])if(b[k]!==undefined)c[k]=String(b[k]).trim();await save(db);return json(res,200,c)}
if(p==='/api/b2b/members'&&req.method==='POST'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u);if(!c||c.owner_user_id!==u.id)return json(res,403,{error:'Only the company owner can add staff'});const b=await body(req),name=String(b.name||'').trim(),email=String(b.email||'').toLowerCase().trim(),password=b.password;if(!name||!validEmail(email)||!strongPassword(password))return json(res,400,{error:'Valid name, email and strong password are required'});if(db.users.some(x=>x.email===email))return json(res,409,{error:'Email already in use'});const staff={id:id(db,'user'),name,email,password_hash:hash(password),role:'b2b_staff',phone:String(b.phone||''),company_id:c.id,created_at:now()};db.users.push(staff);db.b2bMembers.push({id:id(db,'b2bMember'),company_id:c.id,user_id:staff.id,role:'staff',created_at:now()});await save(db);return json(res,201,{user:pub(staff)})}
if(p.match(/^\/api\/b2b\/members\/\d+$/)&&req.method==='DELETE'){const u=b2bAllowed(req,res);if(!u)return;const c=b2bCompanyFor(u);if(!c||c.owner_user_id!==u.id)return json(res,403,{error:'Only the company owner can remove staff'});const mid=Number(p.split('/').pop()),m=db.b2bMembers.find(x=>x.id===mid&&x.company_id===c.id);if(!m)return json(res,404,{error:'Team member not found'});const staff=db.users.find(x=>x.id===m.user_id);if(staff?.id===c.owner_user_id)return json(res,400,{error:'Company owner cannot be removed'});db.b2bMembers=db.b2bMembers.filter(x=>x.id!==m.id);db.sessions=db.sessions.filter(x=>x.userId!==m.user_id);db.users=db.users.filter(x=>x.id!==m.user_id);await save(db);return json(res,204,{})}
return json(res,404,{error:'API route not found'});
}catch(e){console.error(e);return json(res,500,{error:'Server error'})}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return api(req,res,url);sendFile(req,res)});
(async()=>{db=await load();await ensureAdmin();server.listen(PORT,()=>console.log(`PHOENIX GARAGE Phase 16 running at http://localhost:${PORT} (${usePostgres?'postgresql':'sqlite'})`));})().catch(err=>{console.error('Database startup failed:',err);process.exit(1)});
